x=[10,209,378,3878,89,0]
max_value=max(x)
min_value=min(x)
m=sorted(x)
n=len(x)
b=sum(x)
a=any(x)
c=all(x)
print(a)
print(c)
print("sum",b)
print("length",n)
print("sorted value",m)
print("max value",max_value)
print("min value",min_value)
print(pow(2,3))
print(round(8.898898,3))
